### ISSUE TITLE
[CLOSED] Failure loading api endpoint for contacts

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#255]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Sep 28, 2017 at 11:51 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/175_

----

![screen shot 2017-09-28 at 5 47 51 am](https://user-images.githubusercontent.com/7318348/30964970-c5630ff2-a410-11e7-8dab-f735fb3ca679.png)

Soon after a new install I often get this on the contacts list page. "Failed to load resource: the server responded with a status of 500 " 

I don't know if this is a local issue on my machine or something else. 

@corsacca Can you look at this? Or are you seeing this in your environment?

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Thursday Sep 28, 2017 at 13:01 GMT_

----

@ChrisChasm I reset my system and can't seem to reproduce it. We you see it next can you post the trace log and error message from the server?

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Thursday Sep 28, 2017 at 13:06 GMT_

----

```
[28-Sep-2017` 13:04:29 UTC] PHP Fatal error:  Uncaught Error: Expected yes or no, instead got No in /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-contacts/contacts-endpoints.php:342
Stack trace:
#0 /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-contacts/contacts-endpoints.php(320): Disciple_Tools_Contacts_Endpoints::yes_no_to_boolean('No')
#1 /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-contacts/contacts-endpoints.php(462): Disciple_Tools_Contacts_Endpoints->add_related_info_to_contacts(Array)
#2 /Documents/PROJECTS/localhost/wp-includes/rest-api/class-wp-rest-server.php(947): Disciple_Tools_Contacts_Endpoints->get_viewable_contacts(Object(WP_REST_Request))
#3 /Documents/PROJECTS/localhost/wp-includes/rest-api/class-wp-rest-server.php(329): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /Documents/PROJECTS/localhost/wp-includes/rest-api.php(271): WP_REST_Server->serve_request('/dt-hooks/v1/co...')
#5 /Users/ch in /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-contacts/contacts-endpoints.php on line 342
```

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Thursday Sep 28, 2017 at 13:20 GMT_

----

That first line is important. Some field in saved as "No" instead of "no". Do you know which one?

**Comment by corsacca** [comment]
<a href="https://github.com/corsacca"><img src="https://avatars1.githubusercontent.com/u/24901539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [corsacca](https://github.com/corsacca)**
_Thursday Sep 28, 2017 at 13:41 GMT_

----

@ChrisChasm i remove the only place i could find that sets a "No" If you still get it, can you tell me what field is throwing the error?
