### ISSUE TITLE
[CLOSED] Fatal Error with Migration Lock

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#259]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrisChasm](https://github.com/ChrisChasm)**
_Friday Sep 29, 2017 at 18:02 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/180_

----

I got this fatal error when I was deactivating and reactivating the Disciple Tools plugin. I had to comment out the migration class inside Activate to get the system to come back up.

<img width="1522" alt="screen shot 2017-09-29 at 11 53 29 am" src="https://user-images.githubusercontent.com/7318348/31028874-de089ade-a50c-11e7-98a6-82b0f542f70f.png">

```
( ! ) Fatal error: Uncaught Exception: Cannot migrate, as migration lock is held in /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-core/admin/class-migration-engine.php on line 81
( ! ) Exception: Cannot migrate, as migration lock is held in /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-core/admin/class-migration-engine.php on line 81
Call Stack
#	Time	Memory	Function	Location
1	0.0018	476320	{main}( )	.../plugins.php:0
2	0.3222	23411952	do_action( )	.../plugins.php:166
3	0.3222	23412328	WP_Hook->do_action( )	.../plugin.php:453
4	0.3222	23412328	WP_Hook->apply_filters( )	.../class-wp-hook.php:323
5	0.3222	23413456	disciple_tools_activate( )	.../class-wp-hook.php:298
6	0.3227	23468928	Disciple_Tools_Activator::activate( )	.../disciple-tools.php:52
7	0.4612	28668728	Disciple_Tools_Migration_Engine::migrate( )	.../class-activator.php:62
```

Debug Log
```
[29-Sep-2017 17:57:51 UTC] PHP Fatal error:  Uncaught Exception: Cannot migrate, as migration lock is held in /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-core/admin/class-migration-engine.php:81
Stack trace:
#0 /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-core/admin/class-activator.php(62): Disciple_Tools_Migration_Engine::migrate(0)
#1 /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/disciple-tools.php(52): Disciple_Tools_Activator::activate(false)
#2 /Documents/PROJECTS/localhost/wp-includes/class-wp-hook.php(298): disciple_tools_activate(false)
#3/Documents/PROJECTS/localhost/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 Documents/PROJECTS/localhost/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 Documents/PROJECTS/localhost/wp-admin/includes/plugin.php(591): do_action('activate_discip...', false)
#6/Documents/PROJECTS/localhost/wp-content/themes/di in /Documents/PROJECTS/localhost/wp-content/plugins/disciple-tools/dt-core/admin/class-migration-engine.php on line 81
```

**Comment by corsacca** [comment]
<a href="https://github.com/ChrisChasm"><img src="https://avatars3.githubusercontent.com/u/7318348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisChasm](https://github.com/ChrisChasm)**
_Saturday Sep 30, 2017 at 16:27 GMT_

----

I have rebuilt my local machine couple times. I have not seen this error come up again. I’m going to close it because it might have been isolated to dev garbage in an earlier system state.
